import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/components/AuthSessionProvider";
import clsx from "clsx";
import { ToastContainer } from "react-toastify";

const outfitFont = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={clsx("h-full antialiased", outfitFont.variable)}>
      <body className="flex min-h-full flex-col">
        <ToastContainer />
        <AuthSessionProvider>{children}</AuthSessionProvider>
      </body>
    </html>
  );
}
